### ISSUE TITLE
Change parser to new language proposal

### ISSUE THREAD

**Issue by rodrigosetti** [rodrigosetti/master-plan#5]
@wiz has made a proposal for new .plan language:

https://gist.github.com/wiz/fd7249de5485f52e3102c0773fc1daff

which is much better because it enforces (what I think is) good practice of defining properties together, and also I think is more readable.

**Comment by wiz** [comment]
To confess, I really had no idea were to put the actual algebra bits.

I thought about making a keyword or something, but it doesn't quite fit the bag-of-attributes style of the rest. 
Then I tried to interject between the node name and its attributes (`step_one_of_many something + more { ... }`), it didn't felt like it, so I just dumped it at exrpression's end.

And someone noted it turned to be something akin to XML notation, if you squint a little: `<step title="title" ...>x + y</step>` and XML's are related to s-expressions. Here's [his take at it](http://lpaste.net/357686), in some imaginary LISP flavour. I'm not a huge fan of such, but maybe it'd inspire you to something.

Another option is, of course, to retain the `=` symbol for binding blocks together. Maybe it is reasonable to have both inlined and free-standing expressions.

**Comment by rodrigosetti** [comment]
I think as a core syntax your proposal is great - I like the minimalism. The "=" bindings can came later, if necessary... I think I need to use this for a while for my real plannings to know if it's desirable.

I slightly prefer curly than square brackets between attributes - just because is more common in general; but for sure parenthesis in the expressions - otherwise is too odd.
